name: 'PR Validation'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_checks.yml@1.4.2
    secrets: inherit
    with:
      checkLabels: true
