name: 'Terraform GitHub Actions'
on:
  pull_request:
    branches:
      - master
jobs:
  fmt:
    name: 'terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Terraform Format'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'fmt'

  DNS:
    name: 'DNS'
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init for generate certificate dns'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/generate-certificate-dns

      - name: 'Terraform validate for generate certificate dns'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/generate-certificate-dns

      - name: 'Terraform plan for generate certificate dns'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/generate-certificate-dns
  Email:
    name: 'DNS'
    needs: fmt
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init for generate certificate email'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/generate-certificate-email

      - name: 'Terraform validate for generate certificate email'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/generate-certificate-email

      - name: 'Terraform plan for generate certificate email'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/generate-certificate-email

  pre-commit:
    name: 'Pre-Commit'
    needs:
      - fmt
      - plan
      - validate
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Install Tflint'
        run: |
          curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: 'Pre-Commit 🔎'
        uses: pre-commit/action@v2.0.3
        continue-on-error: true
