name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-checks-generate-certificate-dns-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.2
    with:
      working_directory: './_example/generate-certificate-dns/'
  tf-checks-generate-certificate-email-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.2
    with:
      working_directory: './_example/generate-certificate-email/'
  tf-checks-import-certificate-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.2
    with:
      working_directory: './_example/import-certificate/'



